Repository storybookjs/marksy, pull requests merged in 2020-11, with the labels that each got.

#144 fix(deps): update marked dependency
  package.json
  src/__snapshots__/index.test.js.snap
  src/index.test.js
  yarn.lock
Labels: dependencies, security

#141 test: fix typo
  src/index.test.js
Labels: ci running, testing

#147 chore: add CodeQL Analysis
  .github/workflows/codeql-analysis.yml
Labels: chore, security
